// 体验中心页面
export default {
  title: 'Welcome to BigModel Platform! 👋',
  introduction:
    'Here, you can quickly test the effects of models in business scenarios and experience various large models provided by the platform.',
  welcome_title: 'Start with {0} Unleash Your Ideas',
  text_model: 'Text Model',
  multimodal_model: 'Multi-modal Model',
  image_model: 'Image Model',
  video_model: 'Video Model',
  voice_model: 'Voice Model',
  visual_model: 'Vision Model',
  add_model: 'Compare models',
  ai_mark_text: 'Generated by AI within the platform, does not represent the stance of developers.',
  chat_record: 'Conversation Record',
  chat_record_tip: 'Maximum of one month of conversation records retained',
  chat_empty_text: 'No records found',
  default_chat_title: 'New Conversation',
  new_session: 'New conversation',
  new_session_tip: 'A new conversation has started',
  clear_chat: {
    text: 'Clear Conversation',
    title: 'Clear All',
    desc: 'Are you sure you want to clear all conversations?'
  },
  model_setting: {
    title: 'Model Parameter Settings',
    view_code: 'View Code',
    sync_config: 'Sync Parameters',
    sync_config_tip:
      'Migrate the same type of parameters to other models to avoid redundant configuration.',
    parameter_config: 'Parameter Configuration',
    parameter_config_tip: 'Set up after selecting a model',
    sys_prompt: 'System Prompt',
    role_define: 'Custom Role Definition',
    resolution: 'Size',
    resolution_desc: 'Select image resolution.',
    video: {
      ai_sound: 'AI Sound',
      ai_sound_desc:
        'Using AI to create sound effects for generated videos, enhancing their immersion and expressiveness.',
      gen_mode: 'Gen mode',
      gen_mode_desc:
        'Quality First: Generate video with better image quality.<br/>Speed First: Generate video faster, relatively reducing video image quality.',
      gen_mode_desc3:
        'Quality First: Generate video with better image quality, This mode does not support the first and last frames. <br/>Speed First: Generate video faster, relatively reducing video image quality. This mode support the first and last frames.',
      quality: 'Quality first',
      quality_warning: 'This mode does not support the first and last frames.',
      speed: 'Speed first',
      frame_rate: 'Frame Rate',
      frame_rate_desc:
        'The number of image frames displayed per second, determining the smoothness of a video, commonly measured in fps.',
      fps_30: '30 FPS',
      fps_60: '60 FPS',
      resolution: 'Resolution',
      resolution_desc:
        "The default generated video has a short side of 1080, with the long side scaled according to the original image's aspect ratio. Up to 4K resolution is supported.",
      duration: 'Duration',
      duration_desc: 'Duration of the Generated Video'
    },
    tool_function_desc:
      'Enter a tool name or a list of tool descriptions separated by commas. For more details, please refer to the documentation{0}.',
    function_define: 'Function Definition',
    example_function: 'Function Example',
    search_options: [
      { label: 'Zhipu Search Std', value: 'search_std' },
      { label: 'Zhipu Search Pro', value: 'search_pro' },
      { label: 'Sogou Search', value: 'search_pro_sogou' },
      { label: 'Quark Search', value: 'search_pro_quark' }
      // { label: 'Jina AI', value: 'search_pro_jina' },
      // { label: 'Bing', value: 'search_pro_bing' }
    ]
  },
  select_model: 'Select Model',
  selected_num: 'Selected {0}/{1}',
  delete_model_title: 'Remove this model?',
  delete_model_desc: 'Removing will not save historical conversation records',
  switch_model: 'Switch Model',
  no_fintune_task: 'No fine-tune tasks',
  no_private_task: 'No private tasks',
  more_model: 'More Model',
  total_model_num: '({0} models)',
  total_model_num_radio: '{0} models',
  total_model_num_new: '{0} models available. Select 1–3.',
  search_model_empty: 'No related models found',
  model_category: {
    language: 'Language Model',
    scence_model: 'Perception Model',
    image2text: 'Image-to-Text Model',
    text2image: 'Text-to-Image Model',
    text2video: 'Text-to-Video Model',
    fintune: 'Fine-tune model',
    private: 'Private model',
    audio: 'Audio Model'
  },
  model_content: {
    slef_model: 'Model repository',
    model_square: 'Foundation models',
    fine_tune_model: 'Fine-tune model',
    private_mode: 'Private model'
  },
  welcome: {
    text: [
      {
        label: 'GLM-4-Plus',
        modelCode: 'glm-4-plus',
        tags: ['High-Intelligent Flagship'],
        desc: 'Leveraging extensive model-assisted generation of high-quality synthetic data to enhance performance, and utilizing PPO to effectively improve reasoning capabilities, GLM-4-Plus has achieved performance on par with top-tier models such as GPT-4o across various benchmarks.'
      },
      {
        label: 'GLM-Z1-Air',
        modelCode: 'glm-z1-air',
        tags: ['Supports complex reasoning'],
        desc: 'A fully self-developed 32B parameter GLM inference model with performance comparable to DeepSeek-R1, at only 1/30th of the cost.'
      },
      {
        label: 'GLM-4-Flash',
        modelCode: 'glm-4-flash',
        tags: ['Fast Response & Free'],
        desc: 'A free and user-friendly language model suitable for handling simple tasks, such as intelligent Q&A, summarization, and text data processing across various applications.'
      }
    ],
    multimodal: [
      {
        label: 'GLM-4V-Plus-0111',
        modelCode: 'glm-4v-plus-0111',
        tags: ['Visual Understanding'],
        desc: 'Possesses strong capabilities in complex semantic alignment and instruction following, supporting bilingual input in Chinese and English of any length. It can generate images in multiple resolutions while also demonstrating strong text generation abilities.'
      },
      {
        label: 'Cogview-4-250304',
        modelCode: 'cogview-4-250304',
        tags: ['High-Precision Image Generation'],
        desc: 'Possesses strong capabilities in complex semantic alignment and instruction following, supports bilingual input in Chinese and English of any length, and can generate images in multiple resolutions while demonstrating robust text generation abilities.'
      },
      {
        label: 'CogvideoX-3',
        modelCode: 'cogvideox-3',
        tags: ['Image/Text-to-Video Generation'],
        desc: 'The video quality is clearer and more stable, supports large-scale movement.'
      }
    ],
    voice: {
      title: 'GLM-4-Voice',
      sub_title: 'Advanced real-time voice model developed by Zhipu AI',
      desc: 'Support real-time voice conversations in Chinese and English.'
    },
    source: '@ZHIPU'
  },
  chat: {
    guide_text:
      'Feel free to chat! You may choose from the following sample questions, or ask yours.',
    default_guide_text:
      'Welcome to experience Zhipu’s large model products. Click below to start interacting and personally feel the infinite charm of intelligent technology!',
    guide_text_4v:
      'The model possesses powerful image understanding and reasoning capabilities, making it highly applicable to various scenarios such as image captioning, chart-based question answering, and text information extraction.',
    comparison_text: 'Synchronize model context: {0}',
    cost_time_text: 'Response Time: {0} ms',
    cost_tokens_text: 'Tokens Used: {0} tokens',
    using_web_search: 'Querying the web search interface...',
    complete_web_search: 'Complete web search: {0}',
    search_result_text:
      'Network search ({0}) finished, showing response above/search results as below.',
    empty_web_search: 'Network search ({0}) finished, no valid results retrieved.',
    search_cost_text: 'Network search time: {0} ms',
    thinking_text: 'Thinking',
    thought_text: 'Model Thought',
    thought_stop_text: 'Processing has been halted.'
  },
  chat_answer: {
    placeholder: 'Please enter the function call result',
    btn: 'Submit',
    mark1:
      'The above content is AI-generated and does not represent the developer’s stance. Please do not delete or modify this mark',
    mark2:
      'The task will not be canceled if you leave this page. Experience center tasks are saved for 24 hours.',
    stoped: 'This answer has been terminated',
    error1: 'Function call result cannot be empty!'
  },
  view_code: {
    title: 'View Code',
    copy_tip: 'You can directly copy the following code to use locally.',
    tip_text:
      'You can find your API in {0}. Please note to use environment variables or other methods to hide your API key.',
    btn: 'here'
  },
  search_box: {
    stop: 'Stop generating',
    again: 'Regenerate',
    enter: 'Send',
    upload_image_video: 'Upload video or image',
    upload_image_video_tip: 'Upload video max {0}, image max {1}',
    placeholder: 'Provide a command, and I can assist with chatting, writing, coding, and more.',
    placeholder_4v: 'Please upload images and provide commands, I can understand',
    placeholder_4v_plus: 'Please upload images and provide commands, I can understand',
    placeholder_voice:
      'Generate and understand bilingual (Chinese-English) sentences via voice commands.',
    placeholder_cogview: 'Generate images from text descriptions.',
    placeholder_cogvideo: 'Create videos from text or images.',
    placeholder_multimodal:
      'Give me a command, and I can process and handle a variety of data types in multimodal categories.',
    placeholder_radio: 'Please record or upload files to convert audio to text',
    file_tooltip: `<strong>Function Description</strong>: File Q&A involves uploading files and extracting the text from them as background information for the large model. Excessive text may result in higher costs. To reduce expenses, it is recommended to use the GLM-4-Flash trial version for testing.<br>
<strong>File Restrictions</strong>: Up to 10 files can be uploaded, with a maximum size of 50M per file and 5M for images. Formats supported include PDF, Word, Excel, PPT, text, and images.`,
    ideas: 'Share your ideas...',
    upload_asr_tip: 'Supports .wav, .mp3 files, up to 1 minute in length.',
    upload_asr_error:
      'The maximum duration for uploading voice messages is 60 seconds. Please delete and upload again',
    upload_audio_ASR_minate: 'Supports .wav, .mp3 files, up to 1 minute in length.',
    uploadImage: 'Upload image',
    new_session: 'New conversation',
    file_num_limt: 'Upload up to {0} files',
    file_size_limt: 'a maximum size of {0} per file, a maximum size of {1} per image',
    file_uploading_tip: 'File is uploading, please wait...',
    upload_audio: 'Supports .wav, .mp3 files, up to 10 minutes in length.',
    audio_limit_tip: 'Up to {0} audio file upload',
    please_start_speaking: 'Please start speaking...'
  },
  function_call: {
    name_error_tip:
      'Name: Can only include a-z,A-Z,0-9, underscores (_), and hyphens (-), with a maximum length of 64.'
  },
  model_tools: {
    tool_select: 'Select Tools',
    title: 'Tool Calls',
    choosePlaceholder: 'Please select a knowledge',
    noContent: 'No content available',
    toCreate: 'Create',
    to_create_fine_tune_model: 'Go to Model Fine-Tuning',
    to_create_private_mode: 'Go to Private Instance Deployment',
    no_fintune_task_model: 'No fine-tuned model available.',
    no_private_task_model: 'No private instance available.',
    toolData: {
      tools4: {
        paramName: 'MCP',
        desc: 'You can interface with the tool service API using the standardized protocol (MCP) to make calls and {0}。',
        link: "check the tool's pricing structure.",
        add: 'Add MCP'
      },
      tools1: {
        paramName: 'Web Search',
        desc: 'Can perform web searches and then pass the search results to the large model for further generation and processing'
      },
      tools2: {
        paramName: 'Knowledge',
        desc: 'Answers user questions by accessing the open platform knowledge base as background knowledge'
      },
      tools3: {
        paramName: 'Function Calling',
        desc: 'Function call enhances model reasoning or performs other external operations, such as information retrieval, database operations, knowledge graph search and reasoning, operating system, triggering external operations, etc.'
      }
    },
    select_mcp: {
      title: 'Select the MCP service',
      tools_num: 'Tools {0}',
      add_mcp_num: 'Added MCP {0}/{1}',
      no_tool_tip: 'The selection of the MCP service tool cannot be empty'
    }
  },
  timbre: {
    title: 'Timbre',
    tongtong: 'Tong tong',
    female: 'Female',
    male: 'Male'
  },
  request_info: {
    video_fail: 'A video is currently being generated, please try again later',
    fail_mess: 'Failed to generate image',
    cancel: 'Cancel request',
    tts_fail: 'Failed to generate',
    audio_fail: 'Failed to generate voice, please try on'
  },
  // 额外信息
  extra: {
    clickEdit: 'Click to edit function',
    editFun: 'Edit Function',
    enterCode: 'Please enter function code',
    standJson: 'Please enter standard JSON format',
    mustInput: 'Function name must be filled in',
    placeInterFun: 'Please enter function',
    not_support: 'Your browser does not support video playback'
  },
  reload: 'Reload',
  call_mcp_name: 'Call the MCP tool: {0}',
  tokens_cost_tip: 'Experience model will be charged based on actual consumption. Please refer to ',
  pricing_text: 'the product pricing',
  knowledge_setting: {
    title: 'Knowledge Answer',
    go_config: 'Manage knowledge base',
    go_add: 'Create knowledge base'
  },
  search_setting: {
    title: 'Online search',
    search_placeholder: 'Search Tool Selection',
    config: {
      title: 'Configuration',
      paramName1: 'count',
      paramName2: 'Intent',
      paramName3: 'Search recency',
      paramName4: 'Content size',
      paramName5: 'Search domain',
      paramName_des1: 'Number of search results to return，range 1–50, default is 10',
      paramName_des1_10:
        'Number of search results to return，Selectable values: 10, 20, 30, 40, 50; default is 10',
      paramName_des2: 'Whether to perform search intent recognition',
      paramName_des3: 'Search web pages within a specified time range',
      paramName_des4: 'Controls the length of the returned web page content',
      paramName_des5:
        'Restricts search results to a specified range; only one designated whitelisted domain is supported.',
      option: {
        date1: 'Unlimited',
        date2: 'Within a Week',
        date3: 'Within a Month',
        date4: 'Within a Year'
      },
      date_option: [
        { label: 'Unlimited', value: 'noLimit' },
        { label: 'oneDay', value: 'oneDay' },
        { label: 'oneWeek', value: 'oneWeek' },
        { label: 'oneMonth', value: 'oneMonth' },
        { label: 'oneYear', value: 'oneYear' }
      ],
      content_size_option: [
        { label: 'medium', value: 'medium' },
        { label: 'high', value: 'high' }
      ]
    }
  },
  exit_scene: 'Click to exit the scenario case',
  deep_thinking: 'Thinking',
  deep_thinking_tooltip: '  Click to switch to thinking mode',
  deep_thinking_options: [
    {
      label: 'auto',
      value: 'enabled',
      desc: 'Intelligently activate in-depth thinking'
    },
    {
      label: 'disabled',
      value: 'disabled',
      desc: 'Quick and direct answer'
    }
  ],
  ppt: {
    export_pdf: 'Export PDF',
    not_found: 'PPT not found',
    export: 'Export',
    exporting: 'Exporting',
    export_success: 'Export successful',
    export_cancel: 'Export cancelled',
    export_error: 'Export failed, please try again later',
    export_ask:
      'The export process may take some time (estimated 1-10 minutes). You can use other applications, but please do not close this page or browser.',
    export_confirm: 'Confirm Export'
  }
}
